name: Deploy ReserveRecPublic Test

run-name: Deploying ${{ github.ref_name }} (Public) to ReserveRecPublic Test Environment

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      releaseTag:
        description: "Tag of version to be promoted to test"
        required: true

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-reserve-rec-public
  cancel-in-progress: false

env:
  S3_BUCKET: ${{ vars.S3_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: reserveRecPublicTest
    strategy:
      max-parallel: 1
      matrix:
        node-version: [20.x]
    steps:
      ### Restore cdk.out cache
      - name: Restore cdk.out cache
        uses: actions/cache@v4
        with:
          path: cdk.out
          # a static cache key is fine since cdk deploy will overwrite files as needed
          key: ${{ runner.os }}-test-cdk-out
          restore-keys: |
            ${{ runner.os }}-test-cdk-out

      ### Checkout GitHub Repo
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install AWS CDK
        run: |
          yarn
          yarn global add aws-cdk

      ### Assume AWS IAM Role
      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}

      ## CDK Deploy
      - name: CDK Deploy
        run: export LOG_LEVEL=debug && cdk deploy -c @context=test --all --require-approval never --rollback

      ### Save cdk.out cache
      - name: Save cdk.out cache
        uses: actions/cache@v4
        with:
          path: cdk.out
          key: ${{ runner.os }}-test-cdk-out

      ### Install if no cache exists ###
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
      - run: yarn install --silent --frozen-lockfile

      ### Build if no cache exists ###
      - name: Cache Build
        id: cache-build
        uses: actions/cache@v4
        with:
          path: |
            **dist
          key: ${{ github.sha }}-dist
      - name: Run yarn build
        if: steps.cache-build.outputs.cache-hit != 'true'
        env:
          GH_HASH: ${{ github.sha }}
        run: |
          sed 's@localConfigEndpoint@'true'@g' src/env.js.template | sed 's@localGHHash@'"$GH_HASH"'@g' > src/env.js
          yarn build

      ### Upload dist to S3 ###
      - name: Deploy to S3
        env:
          DIR_NAME: ${{ github.sha }}
        run: |
          echo "Deploying to $S3_BUCKET/$DIR_NAME"
          aws s3 sync dist s3://$S3_BUCKET/$DIR_NAME
          aws s3 rm s3://$S3_BUCKET/ --recursive --exclude "*" --include "latest/*"
          aws s3 sync dist s3://$S3_BUCKET/latest

      ### Invalidate CloudFront Cache ###
      - name: Invalidate CloudFront Cache
        env:
          DISTRIBUTION_ID: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          echo "Invalidating CloudFront Distribution ID: $DISTRIBUTION_ID"
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"

